# Generated by Django 3.2.6 on 2021-08-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_poll', '0002_auto_20210816_1240'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('question', 'user'), name='user_question'),
        ),
    ]
